version: '3.3'

volumes:
  volume_mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: ${HOME}/data/mariadb
  volume_wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: ${HOME}/data/wordpress

services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
          DB_NAME: wordpress
          MYSQL_USER: rchampli
          MYSQL_PASSWORD: inception
          MYSQL_ROOT_PASSWORD: inception
    volumes:
      - volume_mariadb:/var/lib/mysql
    networks:
      - docker_network
    restart:  always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: ./requirements/wordpress
      args:
          DB_NAME: wordpress
          MYSQL_USER: rchampli
          MYSQL_PASSWORD: inception
          MYSQL_ROOT_PASSWORD: inception
    volumes:
      - volume_wordpress:/var/www/html
    networks:
      - docker_network
    restart:  always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - docker_network
    volumes:
      - volume_wordpress:/var/www/html
    restart:  always
    
networks:
  docker_network:
    driver: bridge